elasticsearch:
  host: 10.0.26.156
  port: 9200

spring:
  datasource:
    url: jdbc:mysql://10.0.26.156:3307/rkzhk
    username: root
    password: 123root456
    driver-class-name: com.mysql.jdbc.Driver